name: onoo
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  connectivity: ^3.0.6
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.0
  equatable: ^2.0.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter_bloc: ^7.0.0
  flutter_facebook_auth: ^3.5.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.1
  fluttertoast: ^8.0.6
  google_mobile_ads: ^0.13.0
  google_sign_in: ^5.0.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.1
  image_picker: ^0.7.5+2
  intl: ^0.17.0
  intro_slider: ^3.0.2
  launch_review: ^3.0.1
  onesignal_flutter: ^3.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.1
  pin_entry_text_field: ^0.1.4
  pinput: ^1.2.0
  provider: ^5.0.0
  share: ^2.0.1
  url_launcher: ^6.0.3
  youtube_player_flutter: ^8.0.0
  flutter_html: ^2.1.0
  get_it: ^7.1.3
  better_player: ^0.0.72
  sign_in_with_apple: ^3.0.0
  dio: 4.0.0
  flutter_datetime_picker: 1.5.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.0
  build_runner: any
  hive_generator: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: ic_launcher
  image_path: assets/images/android_launcher_icon.jpg
  ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/images/drawer_icon/
    - assets/images/login_screen/
    - assets/images/icons/
    - assets/images/home_screen/
    - assets/images/post_details/
    - lib/languages/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto BoldItalic
      fonts: 
        - asset: fonts/Roboto-BoldItalic.ttf
    - family: Roboto Italic
      fonts: 
        - asset: fonts/Roboto-Italic.ttf
    - family: Roboto Bold
      fonts: 
        - asset: fonts/Roboto-Bold.ttf
    - family: Roboto Medium
      fonts: 
        - asset: fonts/Roboto-Medium.ttf
    - family: Roboto Light
      fonts: 
        - asset: fonts/Roboto-Light.ttf
  uses-material-design: true

